tribe: fix the inclusion of config.h file
This was broken by commit cf1dc27 ("tribe: move the generation of
config.h into the top level CMakeLists.txt file").

This fixes the following error(s):

ninja: job failed: /usr/bin/gcc  -Isrc -I../ -I../src -Wno-unused-parameter -Werror -Wextra -Wall -std=c99  -g -MD -MT src/ui/cli/CMakeFiles/tribecli.dir/main.c.o -MF src/ui/cli/CMakeFiles/tribecli.dir/main.c.o.d -o src/ui/cli/CMakeFiles/tribecli.dir/main.c.o -c ../src/ui/cli/main.c
../src/ui/cli/main.c:7:20: fatal error: config.h: No such file or directory
compilation terminated.

Tested with:

$ rm -r out
$ mkdir out
$ cd out
$ cmake -GNinja -DCMAKE_BUILD_TYPE=Debug ..
$ cd ..
$ ninja -C out

Signed-off-by: Thiago Farina <tfransosi@gmail.com>