sab: use title-style capitalization for "Toolbar Style" menu item
From Microsoft UX checklist:

"Use title-style capitalization for titles, and sentence-style capitalization
for all other UI elements. Doing so is more appropriate for the Windows tone.
Exception: For legacy applications, you may use title-style capitalization
for command buttons, menus, and column headings if necessary to avoid mixing
capitalization styles."

https://learn.microsoft.com/en-us/windows/win32/uxguide/top-violations#text

Microsoft recommends using title-style capitalization for menu items for legacy
applications. Since we are creating an application in a legacy style, let's
go with that exception.

https://learn.microsoft.com/en-us/windows/win32/uxguide/text-ui#capitalization

Signed-off-by: Thiago Farina <tfransosi@gmail.com>